"""Smoke tests for src/sentinel/fixer.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_fixer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.fixer")
    assert mod is not None

def test_build_narrative_debrief_is_callable():
    """Function build_narrative_debrief exists and is callable."""
    import importlib
    mod = importlib.import_module("sentinel.fixer")
    fn = getattr(mod, "build_narrative_debrief", None)
    assert fn is not None, "'build_narrative_debrief' not found in sentinel.fixer"
    assert callable(fn)
