"""Smoke tests for src/sentinel/stigmergy.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_stigmergy():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.stigmergy")
    assert mod is not None
