"""Smoke tests for src/sentinel/severity.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_severity():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.severity")
    assert mod is not None
