"""Smoke tests for src/sentinel/git_ops.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_git_ops():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.git_ops")
    assert mod is not None
