"""Smoke tests for src/sentinel/triage.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_triage():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.triage")
    assert mod is not None

def test_triage_signal_is_callable():
    """Function triage_signal exists and is callable."""
    import importlib
    mod = importlib.import_module("sentinel.triage")
    fn = getattr(mod, "triage_signal", None)
    assert fn is not None, "'triage_signal' not found in sentinel.triage"
    assert callable(fn)

def test_generate_diagnostic_report_is_callable():
    """Function generate_diagnostic_report exists and is callable."""
    import importlib
    mod = importlib.import_module("sentinel.triage")
    fn = getattr(mod, "generate_diagnostic_report", None)
    assert fn is not None, "'generate_diagnostic_report' not found in sentinel.triage"
    assert callable(fn)
