"""Smoke tests for src/sentinel/incidents.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_incidents():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.incidents")
    assert mod is not None
