"""Smoke tests for src/sentinel/llm.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_llm():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.llm")
    assert mod is not None
