"""Smoke tests for src/sentinel/ledger.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_ledger():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.ledger")
    assert mod is not None
