"""Smoke tests for src/sentinel/attribution.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_attribution():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.attribution")
    assert mod is not None
