"""Smoke tests for src/sentinel/contracts.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_contracts():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.contracts")
    assert mod is not None
