"""Smoke tests for src/sentinel/arbiter.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_arbiter():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.arbiter")
    assert mod is not None
