"""Smoke tests for src/sentinel/sentinel.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_sentinel():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.sentinel")
    assert mod is not None
