"""Smoke tests for src/sentinel/watcher.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_watcher():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.watcher")
    assert mod is not None

def test_fingerprint_signal_is_callable():
    """Function fingerprint_signal exists and is callable."""
    import importlib
    mod = importlib.import_module("sentinel.watcher")
    fn = getattr(mod, "fingerprint_signal", None)
    assert fn is not None, "'fingerprint_signal' not found in sentinel.watcher"
    assert callable(fn)
