"""Smoke tests for src/sentinel/api.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_api():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.api")
    assert mod is not None
