"""Smoke tests for src/sentinel/manifest.py (auto-generated by pact adopt)."""

import pytest

def test_import_sentinel_manifest():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sentinel.manifest")
    assert mod is not None
